export const StackConst = {
  BOTTOM_STACK: "BOTTOM_STACK",
  DRAWER_STACK: "DRAWER_STACK",
  NATIVE_STACK: "NATIVE_STACK",
};
export const IconConst = {
  ICON_HOME: require("../assets/imgs/icon_home.png"),
  ICON_SEARCH: require("../assets/imgs/icon_search.png"),
  ICON_SIM: require("../assets/imgs/icon_sim.png"),
  ICON_MARKET: require("../assets/imgs/icon_market.png"),
  ICON_CHAT: require("../assets/imgs/icon_chat.png"),
  ICON_PROFILE: require("../assets/imgs/icon_user.png"),
};
export const BottomScreenConst = {
  HOME_BOTTOM_SCREEN: "Trang chủ",
  PROFILE_BOTTOM_SCREEN: "Hồ sơ",
};

export const CashType = {
  PUSH_ESCROW_MONEY: 1,
  POP_ESCROW_MONEY: 2,
};

export const ApproveType = {
  WAITNG: 1,
  APPROVED: 2,
  REJECTED: 3,
};

export const ScreenConst = {
  HOME_SCREEN: "Trang chủ",
  SEARCH_SCREEN: "Tìm kiếm",
  MARKET_SCREEN: "Chợ SIM",
  CHAT_SCREEN: "Chat",
  PROFILE_SCREEN: "Hồ sơ",
  ORDER_SCREEN: "Đơn hàng",

  CHANGE_PASSWORD: "ChangePassword",
  UPDATE_PROFILE_SCREEN: "UPDATE_PROFILE_SCREEN",
  PURCHASE_SIM: "PURCHASE_SIM",
  PURCHASE_SIMDATA: "PURCHASE_SIMDATA",
  BIDING: "BIDING",
  FILTER: "FILTER",
  FORTUNE_SIM_SCREEN: "FORTUNE_SIM_SCREEN",
  FORTUNE_SIM_DETAIL_SCREEN: "FORTUNE_SIM_DETAIL_SCREEN",

  SIM_CATEGORY_SCREEN: "SIM_CATEGORY_SCREEN",
  INSTALLMENT_SEARCH_SCREEN: "INSTALLMENT_SEARCH_SCREEN",
  INSTALLMENT_MANGER_SCREEN: "INSTALLMENT_MANGER_SCREEN",
  SEARCH_FENGSHUI_SCREEN: "SEARCH_FENGSHUI_SCREEN",
  SEARCH_FORTUNE_SIM_DETAIL_SCREEN: "SEARCH_FORTUNE_SIM_DETAIL_SCREEN",
  COLLABORATION_SCREEN: "COLLABORATION_SCREEN",
  CREATE_COLLABORATION_SCREEN: "CREATE_COLLABORATION_SCREEN",
  COLLAB_GROUP_SCREEN: "COLLAB_GROUP_SCREEN",
  SIM_VALUATION_SCREEN: "SIM_VALUATION_SCREEN",
  ABOUT_SCREEN: "ABOUT_SCREEN",
  NOTIFICATION_SCREEN: "NOTIFICATION_SCREEN",
  NOTIFICATION_DETAIL_SCREEN: "NOTIFICATION_DETAIL_SCREEN",
  GROUP_CHANNEL_LIST: "GROUP_CHANNEL_LIST",
  GROUP_CHANNEL_CREATE: "GROUP_CHANNEL_CREATE",
  GROUP_CHANNEL: "GROUP_CHANNEL",
  PACKAGE_DETAIL_SCREEN: "PACKAGE_DETAIL_SCREEN",
  MY_AUCTION_SCREEN: "MY_AUCTION_SCREEN",
  AUTION_SCREEN: "AUTION_SCREEN",
  AUTION_FILTER_SCREEN: "AUTION_FILTER_SCREEN",
  VNPT_PACKAGE_SCREEN: "VNPT_PACKAGE_SCREEN",
  DATA_PACKAGE_SCREEN: "DATA_PACKAGE_SCREEN",
  TOURIST_PACKAGE_SCREEN: "TOURIST_PACKAGE_SCREEN",

  SIM_DATA_CATEGORY_SCREEN: "SIM_DATA_CATEGORY_SCREEN",
  SIM_DATA_SEARCH_SCREEN: "SIM_DATA_SEARCH_SCREEN",
  SIM_DATA_FILTER_SCREEN: "SIM_DATA_FILTER_SCREEN",

  MY_SIM_SCREEN: "MY_SIM_SCREEN",

  LOGIN_SCREEN: "LOGIN SCREEN",
  REGISTER_SCEEN: "REGISTER_SCREEN",

  ESCROW_PUSH_MANUAL: "ESCROW_PUSH_MANUAL",
};

export const SearchFrameConst = {
  IS_HOMESEARCH: "IS_HOMESEARCH",
  IS_INSTRUCTION: "IS_INSTRUCTION",
  IS_RECENT: "IS_RECENT",
  IS_CATEGORY: "IS_CATEGORY",
  IS_RESULT: "IS_RESULT",
};

export const UltilitiType = {
  SIM_CATEGORY: "SIM_CATEGORY",
  SIM_FORTUNE: "SIM_FORTUNE",
  ABOUT: "ABOUT",
  COLLABORATION: "COLLABORATION",
  SIM_VALUATION: "SIM_VALUATION",
  ORDER: "ORDER",
  SEARCH_FENGSHUI: "SEARCH_FENGSHUI",
  INSTALLMENT_SEARCH: "INSTALLMENT_SEARCH",
  INSTALLMENT_MANAGER: "INSTALLMENT_MANAGER",
  AUTION: "AUTION",
  VNPT_PACKAGE: "VNPT_PACKAGE",
  DATA_PACKAGE: "DATA_PACKAGE",
  TOURIST_PACKAGE: "TOURIST_PACKAGE",
  SIM_DATA_CATEGORY: "SIM_DATA_CATEGORY",
};
export const AppConst = {
  StackConst,
  BottomScreenConst,
  ScreenConst,
  IconConst,
  SearchFrameConst,
  UltilitiType,
  CashType,
  ApproveType,
};
